services:
  postgres:
    image: postgres:18
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=relay
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data:
